In [1]:
paragraph = """Narendra Damodardas Modi (Gujarati: born 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation. He is the first prime minister to have been born after India's independence in 1947 and the second prime minister not belonging to the Indian National Congress to have won two consecutive majorities in the Lok Sabha, or the lower house of India's parliament. He is also the longest serving prime minister from a non-Congress party.
Born and raised in Vadnagar, a small town in northeastern Gujarat, Modi completed his secondary education there. He was introduced to the RSS at age eight. He has drawn attention to having to work as a child in his father's tea stall on the Vadnagar railway station platform, a description that has not been reliably corroborated. At age 18, Modi was married to Jashodaben Chimanlal Modi, whom he abandoned soon after. He left his parental home where she had come to live. He first publicly acknowledged her as his wife more than four decades later when required to do so by Indian law, but has made no contact with her since. Modi has asserted he had travelled in northern India for two years after leaving his parental home, visiting a number of religious centres, but few details of his travels have emerged. Upon his return to Gujarat in 1971, he became a full-time worker for the RSS. After the state of emergency was declared by prime minister Indira Gandhi in 1975, Modi went into hiding. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary"""

In [2]:
paragraph

"Narendra Damodardas Modi (Gujarati: born 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation. He is the first prime minister to have been born after India's independence in 1947 and the second prime minister not belonging to the Indian National Congress to have won two consecutive majorities in the Lok Sabha, or the lower house of India's parliament. He is also the longest serving prime minister from a non-Congress party.\nBorn and raised in Vadnagar, a small town in northeastern Gujarat, Modi completed his secondary education there. He was introduced to the RSS at age eight. He has drawn attention to having to work as a child in his father's tea stall on the V

In [3]:
import nltk
from nltk.stem import PorterStemmer

In [4]:
from nltk.corpus import stopwords

In [5]:
## Tokenization -> paragraph into 
# nltk.download('punkt') to use tokeniziing

sentences = nltk.sent_tokenize(paragraph)

In [6]:
sentences

['Narendra Damodardas Modi (Gujarati: born 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014.',
 'Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi.',
 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation.',
 "He is the first prime minister to have been born after India's independence in 1947 and the second prime minister not belonging to the Indian National Congress to have won two consecutive majorities in the Lok Sabha, or the lower house of India's parliament.",
 'He is also the longest serving prime minister from a non-Congress party.',
 'Born and raised in Vadnagar, a small town in northeastern Gujarat, Modi completed his secondary education there.',
 'He was introduced to the RSS at age eight.',
 "He has drawn attention to having to work as a child in his

In [7]:
sentences[0]

'Narendra Damodardas Modi (Gujarati: born 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014.'

In [8]:
stemmer = PorterStemmer()

In [9]:
stemmer.stem('history')

'histori'

In [10]:
from nltk.stem import WordNetLemmatizer
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [11]:
lemmatizer = WordNetLemmatizer()

In [12]:
lemmatizer.lemmatize('goes')

'go'

In [13]:
## Removing special characters
import re
corpus = []
for sentence in sentences:
    result = re.sub('[^a-zA-Z]', ' ', sentence)
    corpus.append(result.lower().split())


In [14]:
corpus

[['narendra',
  'damodardas',
  'modi',
  'gujarati',
  'born',
  'september',
  'a',
  'is',
  'an',
  'indian',
  'politician',
  'serving',
  'as',
  'the',
  'th',
  'and',
  'current',
  'prime',
  'minister',
  'of',
  'india',
  'since'],
 ['modi',
  'was',
  'the',
  'chief',
  'minister',
  'of',
  'gujarat',
  'from',
  'to',
  'and',
  'is',
  'the',
  'member',
  'of',
  'parliament',
  'from',
  'varanasi'],
 ['he',
  'is',
  'a',
  'member',
  'of',
  'the',
  'bharatiya',
  'janata',
  'party',
  'bjp',
  'and',
  'of',
  'the',
  'rashtriya',
  'swayamsevak',
  'sangh',
  'rss',
  'a',
  'right',
  'wing',
  'hindu',
  'nationalist',
  'paramilitary',
  'volunteer',
  'organisation'],
 ['he',
  'is',
  'the',
  'first',
  'prime',
  'minister',
  'to',
  'have',
  'been',
  'born',
  'after',
  'india',
  's',
  'independence',
  'in',
  'and',
  'the',
  'second',
  'prime',
  'minister',
  'not',
  'belonging',
  'to',
  'the',
  'indian',
  'national',
  'congress',


In [15]:
## Removing the stopwords
stopword = stopwords.words('english')
w_list = []
for word_list in corpus:
    words = []
    for word in word_list:
        if word not in stopword:
            words.append(word)
    w_list.append(words)

In [16]:
corpus = w_list

In [17]:
corpus

[['narendra',
  'damodardas',
  'modi',
  'gujarati',
  'born',
  'september',
  'indian',
  'politician',
  'serving',
  'th',
  'current',
  'prime',
  'minister',
  'india',
  'since'],
 ['modi', 'chief', 'minister', 'gujarat', 'member', 'parliament', 'varanasi'],
 ['member',
  'bharatiya',
  'janata',
  'party',
  'bjp',
  'rashtriya',
  'swayamsevak',
  'sangh',
  'rss',
  'right',
  'wing',
  'hindu',
  'nationalist',
  'paramilitary',
  'volunteer',
  'organisation'],
 ['first',
  'prime',
  'minister',
  'born',
  'india',
  'independence',
  'second',
  'prime',
  'minister',
  'belonging',
  'indian',
  'national',
  'congress',
  'two',
  'consecutive',
  'majorities',
  'lok',
  'sabha',
  'lower',
  'house',
  'india',
  'parliament'],
 ['also',
  'longest',
  'serving',
  'prime',
  'minister',
  'non',
  'congress',
  'party'],
 ['born',
  'raised',
  'vadnagar',
  'small',
  'town',
  'northeastern',
  'gujarat',
  'modi',
  'completed',
  'secondary',
  'education'],
 

In [18]:
## Now applly into stemming
stemmer = PorterStemmer()
stemmed_corpus = []
for words in corpus:
    lst = []
    for word in words:
        lst.append(stemmer.stem(word))
    stemmed_corpus.append(lst)
stemmed_corpus

[['narendra',
  'damodarda',
  'modi',
  'gujarati',
  'born',
  'septemb',
  'indian',
  'politician',
  'serv',
  'th',
  'current',
  'prime',
  'minist',
  'india',
  'sinc'],
 ['modi', 'chief', 'minist', 'gujarat', 'member', 'parliament', 'varanasi'],
 ['member',
  'bharatiya',
  'janata',
  'parti',
  'bjp',
  'rashtriya',
  'swayamsevak',
  'sangh',
  'rss',
  'right',
  'wing',
  'hindu',
  'nationalist',
  'paramilitari',
  'volunt',
  'organis'],
 ['first',
  'prime',
  'minist',
  'born',
  'india',
  'independ',
  'second',
  'prime',
  'minist',
  'belong',
  'indian',
  'nation',
  'congress',
  'two',
  'consecut',
  'major',
  'lok',
  'sabha',
  'lower',
  'hous',
  'india',
  'parliament'],
 ['also', 'longest', 'serv', 'prime', 'minist', 'non', 'congress', 'parti'],
 ['born',
  'rais',
  'vadnagar',
  'small',
  'town',
  'northeastern',
  'gujarat',
  'modi',
  'complet',
  'secondari',
  'educ'],
 ['introduc', 'rss', 'age', 'eight'],
 ['drawn',
  'attent',
  'work',

In [19]:
## Lematize the words
lemmatizer = WordNetLemmatizer()
lemmatized_corpus = []
for words in corpus:
    lst = []
    for word in words:
        lst.append(lemmatizer.lemmatize(word))
    lemmatized_corpus.append(lst)
lemmatized_corpus

[['narendra',
  'damodardas',
  'modi',
  'gujarati',
  'born',
  'september',
  'indian',
  'politician',
  'serving',
  'th',
  'current',
  'prime',
  'minister',
  'india',
  'since'],
 ['modi', 'chief', 'minister', 'gujarat', 'member', 'parliament', 'varanasi'],
 ['member',
  'bharatiya',
  'janata',
  'party',
  'bjp',
  'rashtriya',
  'swayamsevak',
  'sangh',
  'r',
  'right',
  'wing',
  'hindu',
  'nationalist',
  'paramilitary',
  'volunteer',
  'organisation'],
 ['first',
  'prime',
  'minister',
  'born',
  'india',
  'independence',
  'second',
  'prime',
  'minister',
  'belonging',
  'indian',
  'national',
  'congress',
  'two',
  'consecutive',
  'majority',
  'lok',
  'sabha',
  'lower',
  'house',
  'india',
  'parliament'],
 ['also',
  'longest',
  'serving',
  'prime',
  'minister',
  'non',
  'congress',
  'party'],
 ['born',
  'raised',
  'vadnagar',
  'small',
  'town',
  'northeastern',
  'gujarat',
  'modi',
  'completed',
  'secondary',
  'education'],
 ['in

In [20]:
new_corpus = []
for words in stemmed_corpus:
    new_corpus.append(' '.join(words))

In [21]:
new_corpus

['narendra damodarda modi gujarati born septemb indian politician serv th current prime minist india sinc',
 'modi chief minist gujarat member parliament varanasi',
 'member bharatiya janata parti bjp rashtriya swayamsevak sangh rss right wing hindu nationalist paramilitari volunt organis',
 'first prime minist born india independ second prime minist belong indian nation congress two consecut major lok sabha lower hous india parliament',
 'also longest serv prime minist non congress parti',
 'born rais vadnagar small town northeastern gujarat modi complet secondari educ',
 'introduc rss age eight',
 'drawn attent work child father tea stall vadnagar railway station platform descript reliabl corrobor',
 'age modi marri jashodaben chimanl modi abandon soon',
 'left parent home come live',
 'first publicli acknowledg wife four decad later requir indian law made contact sinc',
 'modi assert travel northern india two year leav parent home visit number religi centr detail travel emerg',
 'up

In [22]:
## Bag of words -> CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [85]:
cv = CountVectorizer()

In [90]:
X = cv.fit_transform(new_corpus)

In [91]:
cv.vocabulary_

{'narendra': 67,
 'damodarda': 23,
 'modi': 66,
 'gujarati': 39,
 'born': 11,
 'septemb': 100,
 'indian': 48,
 'politician': 80,
 'serv': 101,
 'th': 111,
 'current': 22,
 'prime': 82,
 'minist': 65,
 'india': 47,
 'sinc': 103,
 'chief': 13,
 'gujarat': 38,
 'member': 64,
 'parliament': 77,
 'varanasi': 118,
 'bharatiya': 9,
 'janata': 51,
 'parti': 78,
 'bjp': 10,
 'rashtriya': 87,
 'swayamsevak': 109,
 'sangh': 96,
 'rss': 94,
 'right': 92,
 'wing': 123,
 'hindu': 43,
 'nationalist': 69,
 'paramilitari': 75,
 'volunt': 120,
 'organis': 74,
 'first': 33,
 'independ': 46,
 'second': 97,
 'belong': 8,
 'nation': 68,
 'congress': 18,
 'two': 115,
 'consecut': 19,
 'major': 62,
 'lok': 58,
 'sabha': 95,
 'lower': 60,
 'hous': 45,
 'also': 3,
 'longest': 59,
 'non': 70,
 'rais': 85,
 'vadnagar': 117,
 'small': 104,
 'town': 113,
 'northeastern': 71,
 'complet': 17,
 'secondari': 98,
 'educ': 29,
 'introduc': 50,
 'age': 2,
 'eight': 30,
 'drawn': 28,
 'attent': 6,
 'work': 125,
 'child': 1

In [95]:
new_corpus[4]

'also longest serv prime minist non congress parti'

In [98]:
X[3].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 2,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [99]:
# There are 2 some where
# Now doing binary

In [100]:
cvv = CountVectorizer(binary=True)

In [103]:
XX = cvv.fit_transform(new_corpus)

In [104]:
XX[3].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [105]:
# Now 2 is changed to 1

## n-grams

In [23]:
# Genereating n-grams
CV = CountVectorizer(binary=True, ngram_range=(3, 3)) # it will create tri-grams
A = CV.fit_transform(new_corpus)

In [25]:
CV.vocabulary_

{'narendra damodarda modi': 80,
 'damodarda modi gujarati': 22,
 'modi gujarati born': 77,
 'gujarati born septemb': 38,
 'born septemb indian': 13,
 'septemb indian politician': 116,
 'indian politician serv': 50,
 'politician serv th': 93,
 'serv th current': 118,
 'th current prime': 126,
 'current prime minist': 21,
 'prime minist india': 97,
 'minist india sinc': 70,
 'modi chief minist': 75,
 'chief minist gujarat': 15,
 'minist gujarat member': 69,
 'gujarat member parliament': 36,
 'member parliament varanasi': 66,
 'member bharatiya janata': 65,
 'bharatiya janata parti': 8,
 'janata parti bjp': 53,
 'parti bjp rashtriya': 90,
 'bjp rashtriya swayamsevak': 10,
 'rashtriya swayamsevak sangh': 104,
 'swayamsevak sangh rss': 124,
 'sangh rss right': 114,
 'rss right wing': 112,
 'right wing hindu': 108,
 'wing hindu nationalist': 137,
 'hindu nationalist paramilitari': 41,
 'nationalist paramilitari volunt': 82,
 'paramilitari volunt organis': 87,
 'first prime minist': 30,
 'pri

In [26]:
ccv = CountVectorizer(ngram_range=(1, 3))
B = ccv.fit_transform(new_corpus)

In [27]:
ccv.vocabulary_

{'narendra': 235,
 'damodarda': 72,
 'modi': 220,
 'gujarati': 121,
 'born': 35,
 'septemb': 338,
 'indian': 152,
 'politician': 274,
 'serv': 341,
 'th': 369,
 'current': 69,
 'prime': 280,
 'minist': 207,
 'india': 145,
 'sinc': 349,
 'narendra damodarda': 236,
 'damodarda modi': 73,
 'modi gujarati': 229,
 'gujarati born': 122,
 'born septemb': 40,
 'septemb indian': 339,
 'indian politician': 157,
 'politician serv': 275,
 'serv th': 344,
 'th current': 370,
 'current prime': 70,
 'prime minist': 281,
 'minist india': 214,
 'india sinc': 149,
 'narendra damodarda modi': 237,
 'damodarda modi gujarati': 74,
 'modi gujarati born': 230,
 'gujarati born septemb': 123,
 'born septemb indian': 41,
 'septemb indian politician': 340,
 'indian politician serv': 158,
 'politician serv th': 276,
 'serv th current': 345,
 'th current prime': 371,
 'current prime minist': 71,
 'prime minist india': 284,
 'minist india sinc': 215,
 'chief': 45,
 'gujarat': 114,
 'member': 202,
 'parliament': 264

## Tf-IDF

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
tf = TfidfVectorizer()
X = tf.fit_transform(new_corpus)

In [30]:
X[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.2278311 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.29400923, 0.29400923, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.29400923,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.2278311 , 0.2278311 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.18911938, 0.17440187, 0.29400923, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [31]:
tf.vocabulary_

{'narendra': 67,
 'damodarda': 23,
 'modi': 66,
 'gujarati': 39,
 'born': 11,
 'septemb': 100,
 'indian': 48,
 'politician': 80,
 'serv': 101,
 'th': 111,
 'current': 22,
 'prime': 82,
 'minist': 65,
 'india': 47,
 'sinc': 103,
 'chief': 13,
 'gujarat': 38,
 'member': 64,
 'parliament': 77,
 'varanasi': 118,
 'bharatiya': 9,
 'janata': 51,
 'parti': 78,
 'bjp': 10,
 'rashtriya': 87,
 'swayamsevak': 109,
 'sangh': 96,
 'rss': 94,
 'right': 92,
 'wing': 123,
 'hindu': 43,
 'nationalist': 69,
 'paramilitari': 75,
 'volunt': 120,
 'organis': 74,
 'first': 33,
 'independ': 46,
 'second': 97,
 'belong': 8,
 'nation': 68,
 'congress': 18,
 'two': 115,
 'consecut': 19,
 'major': 62,
 'lok': 58,
 'sabha': 95,
 'lower': 60,
 'hous': 45,
 'also': 3,
 'longest': 59,
 'non': 70,
 'rais': 85,
 'vadnagar': 117,
 'small': 104,
 'town': 113,
 'northeastern': 71,
 'complet': 17,
 'secondari': 98,
 'educ': 29,
 'introduc': 50,
 'age': 2,
 'eight': 30,
 'drawn': 28,
 'attent': 6,
 'work': 125,
 'child': 1

In [32]:
## ngrams in tfidf
tf = TfidfVectorizer(ngram_range=(1, 3))
Y = tf.fit_transform(new_corpus)

In [33]:
tf.vocabulary_

{'narendra': 235,
 'damodarda': 72,
 'modi': 220,
 'gujarati': 121,
 'born': 35,
 'septemb': 338,
 'indian': 152,
 'politician': 274,
 'serv': 341,
 'th': 369,
 'current': 69,
 'prime': 280,
 'minist': 207,
 'india': 145,
 'sinc': 349,
 'narendra damodarda': 236,
 'damodarda modi': 73,
 'modi gujarati': 229,
 'gujarati born': 122,
 'born septemb': 40,
 'septemb indian': 339,
 'indian politician': 157,
 'politician serv': 275,
 'serv th': 344,
 'th current': 370,
 'current prime': 70,
 'prime minist': 281,
 'minist india': 214,
 'india sinc': 149,
 'narendra damodarda modi': 237,
 'damodarda modi gujarati': 74,
 'modi gujarati born': 230,
 'gujarati born septemb': 123,
 'born septemb indian': 41,
 'septemb indian politician': 340,
 'indian politician serv': 158,
 'politician serv th': 276,
 'serv th current': 345,
 'th current prime': 371,
 'current prime minist': 71,
 'prime minist india': 284,
 'minist india sinc': 215,
 'chief': 45,
 'gujarat': 114,
 'member': 202,
 'parliament': 264

In [34]:
Y[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.12560487, 0.        , 0.        , 0.        , 0.        ,
        0.16208933, 0.16208933, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.16208933,
        0.16208933, 0.16208933, 0.16208933, 0.16

In [35]:
tf = TfidfVectorizer(max_features=5)
Y = tf.fit_transform(new_corpus)

In [36]:
Y[0].toarray()

array([[0.56826099, 0.47170542, 0.4349967 , 0.51512262, 0.        ]])

In [37]:
tf.vocabulary_

{'modi': 2, 'prime': 3, 'minist': 1, 'india': 0, 'rss': 4}

In [38]:
# In max_features, it consider only top assigned max_feaures from corpus of words and gives its output
# In above example top 5 features is selected for all
# All other corpus will be vectorized according to only these vocabulary